import "./globals.css";

import type { Metadata } from "next";
import { GeistSans } from "geist/font/sans";

const geistSans = GeistSans;

export const metadata: Metadata = {
  title: "Resource Hub",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.className} font-sans antialiased`}>
        {children}
      </body>
    </html>
  );
}
